---
name: Packages
on: [workflow_dispatch]
jobs:
  build-sdist:
    name: Build sdist package
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repos
        uses: actions/checkout@v2

      - name: Build sdist
        run: python setup.py sdist

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./dist/*

  build-wheel:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-latest, macos-latest]

    steps:
      - name: Checkout repos
        uses: actions/checkout@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_ARCHS_LINUX: "auto aarch64 ppc64le"
          CIBW_ARCHS_MACOS: "auto universal2"
          CIBW_ARCHS_WINDOWS: "auto"
          CIBW_TEST_EXTRAS: test
          CIBW_TEST_COMMAND: "pytest --color=auto {project}/tests"
          CIBW_TEST_SKIP: "*-macosx_universal2:arm64"

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
